import type { Metadata } from "next";
import "./globals.css";
import Wrapper from "@/lib/Providers/Wrapper";
import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: { colorPrimary: "#7c3aed", colorText: "#ffffff" },
      }}
    >
      <html lang="en">
        <body>
          <Wrapper>
            <main>{children}</main>
          </Wrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
